# Pandas

In [1]:
import pandas as pd
pd.__version__

'1.5.0'

## Series

A Pandas <code>Series</code> is a one-dimensional array of indexed data. It can be created from a list or array as follows:

### Creating a series from list

In [2]:
data_pd = pd.Series([0.25, 0.5, 0.75, 1.0])
print("1: Pandas series from list: \n",data_pd)

1: Pandas series from list:
 0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

### Creating a series from numpy array

In [3]:
import numpy as np
numpy_arr = np.arange(5)
data_pd   = pd.Series(numpy_arr)
print("1: Pandas series from numpy array: \n", data_pd)  # notice default index

1: Pandas series from numpy array:
 0    0
1    1
2    2
3    3
4    4
dtype: int32

### Attributes

In [4]:
print("1: Data values: ", data_pd.values)  # numpy array 
print("2: Data index:  ", data_pd.index)  # range index is pandas object

1: Data values:  [0 1 2 3 4]
2: Data index:   RangeIndex(start=0, stop=5, step=1)

### Indexing

In [5]:
print("1: Data[1]:     ", data_pd[1])
print("2: Data[-2:]: \n", data_pd[-2:])  # slicing still works

# index is explicitly defined!  Unlike numpy which is implicitly defined

# errors, no index of -1
# print("Data[-1]: ", data_pd[-1])

1: Data[1]:      1
2: Data[-2:]:
 3    3
4    4
dtype: int32

### Letter indexing

In [6]:
# integer indexing is nasty!  try change to letters
data_pd = pd.Series([0.25, 0.5, 0.75, 1.0], 
                    index=['a', 'b', 'c', 'd'])

print("1: Data[-1]:  ", data_pd[-1])
print("2: Data['b']: ", data_pd['b'])

1: Data[-1]:   1.0
2: Data['b']:  0.5

### Combined indexing

In [7]:
index   = ['a', 'b', 'c', 'd', 3]
data_pd = pd.Series(numpy_arr, index = index)

print("1: Index['a']: ", data_pd['a'])
print("2: Index[3]:   ", data_pd[3])  # 3 is not position three but index 3!

1: Index['a']:  0
2: Index[3]:    4

### Pandas and dictionary

In [ ]:
# since pandas index system looks like dictionary, it is no surprise
# that pandas can be created from dictionary, see this:
some_population_dict = {'Sai Gon': 11111, 
                        'Vung Tau': 22222,
                        'Phan Thiet': 33333,
                        'Vinh Long': 44444}

data_pd = pd.Series(some_population_dict)
print("1: Population['Vinh Long']: ", data_pd['Vinh Long'])

# also supports slicing!
print("2: Population['Sai Gon':'Vung Tau']: \n", data_pd['Sai Gon': 'Vung Tau'])

1: Population['Vinh Long']:  44444
2: Population['Sai Gon':'Vung Tau']:
 Sai Gon     11111
Vung Tau    22222
dtype: int64

### Pandas and scalar

In [9]:
# data can be scalar, which is repeated to fill the specified index
data_pd = pd.Series(5, index=[2, 3, 8])
print("1: Data pd scalar: \n", data_pd)

1: Data pd scalar:
 2    5
3    5
8    5
dtype: int64

## Dataframe

DataFrame is an analog of a two-dimensional array with both flexible row indices and flexible column names.  DataFrame as a sequence of aligned Series objects.

### Create dataframe with two dict

In [ ]:
some_population_dict = {'Sai Gon': 11111, 
                        'Vung Tau': 22222,
                        'Phan Thiet': 33333,
                        'Vinh Long': 44444}
some_area_dict = {'Sai Gon': 99999, 
                'Vung Tau': 88888,
                'Phan Thiet': 77777,
                'Vinh Long': 66666,
                 'Ben Tre': 33333}

states = pd.DataFrame({'population': some_population_dict,
                       'area': some_area_dict})
print(states)

Everything:
            population   area
Sai Gon        11111.0  99999
Vung Tau       22222.0  88888
Phan Thiet     33333.0  77777
Vinh Long      44444.0  66666
Ben Tre            NaN  33333

### Indexing

In [11]:
print("Only Vung Tau to Sai Gon: ")
print(states['Vung Tau': 'Sai Gon'])

Only Vung Tau to Sai Gon:
Empty DataFrame
Columns: [population, area]
Index: []

In [ ]:
print("Only population column: ")
print(states['Vung Tau': 'Sai Gon']['population'])
print(states['population']['Vung Tau': 'Sai Gon'])  # order does not matter; imagine as drill down

Only population column:
Series([], Name: population, dtype: float64)
Series([], Name: population, dtype: float64)

In [13]:
print("Only area column with everything")
print(states['area'])  # first way
print(states[:]['area']) # second way

Only area column with everything
Sai Gon       99999
Vung Tau      88888
Phan Thiet    77777
Vinh Long     66666
Ben Tre       33333
Name: area, dtype: int64
Sai Gon       99999
Vung Tau      88888
Phan Thiet    77777
Vinh Long     66666
Ben Tre       33333
Name: area, dtype: int64

### Attributes

In [14]:
print("Index:        ", states.index)  # pandas index object
print("Index[-1]:    ", states.index[-1])  # pandas index object is similar to numpy array
print("Columns:      ", states.columns)  # pandas index object
print("Columns[0:1]: ", states.columns[0:1]) # notice how 1 is not included

Index:         Index(['Sai Gon', 'Vung Tau', 'Phan Thiet', 'Vinh Long', 'Ben Tre'], dtype='object')
Index[-1]:     Ben Tre
Columns:       Index(['population', 'area'], dtype='object')
Columns[0:1]:  Index(['population'], dtype='object')

### Other ways to create

In [15]:
# from series
population_series = pd.Series(some_population_dict)
pd_from_series    = pd.DataFrame(population_series, columns=['population'])  # since it's series, we need to pass column name, if not, it will be named 0
print("PD from series: \n", pd_from_series)

# from list of dicts
data              = [{'a': i, 'b': 2 * i} for i in range(3)]
pd_from_list_dict = pd.DataFrame(data, index=[1, 2, 3])
print("PD from list of dict: \n", pd_from_list_dict)

# from 2D numpy array
data_numpy    = np.random.rand(3, 2)
index         = ['a', 'b', 'c']
columns       = ['foo', 'bar']
pd_from_numpy = pd.DataFrame(data_numpy, index=index, columns=columns)
print("PD from numpy: \n", pd_from_numpy)

PD from series:
             population
Sai Gon          11111
Vung Tau         22222
Phan Thiet       33333
Vinh Long        44444
PD from list of dict:
    a  b
1  0  0
2  1  2
3  2  4
PD from numpy:
         foo       bar
a  0.356639  0.370412
b  0.043366  0.577092
c  0.869384  0.314641

 ## Series indexing/slicing/fancy Indexing

In [16]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index = ['a', 'b', 'c', 'd'])

print("Data:\n", data)

Data:
 a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

### Explicit vs. Implicit index

In [17]:
# explicit index
print("Explicit index: ", data['b'])

# also support implicit index, since we define index
print("Implicit index: ", data[-1])

Explicit index:  0.5
Implicit index:  1.0

In [18]:
# slicing with explicit index (include c)
print("Data['a':'c']: \n", data['a':'c'])

# slicing with implicit index (exclude 2)
print("Data[0:2]: \n", data[0:2])

Data['a':'c']:
 a    0.25
b    0.50
c    0.75
dtype: float64
Data[0:2]:
 a    0.25
b    0.50
dtype: float64

### Adding values

In [19]:
# extend series by assigning new index value
data['e'] = 99
print("Data with e: \n", data)

Data with e:
 a     0.25
b     0.50
c     0.75
d     1.00
e    99.00
dtype: float64

### "in"

In [20]:
print("a in data?: ", 'a' in data)  # access keys

a in data?:  True

### keys()

In [21]:
print("All keys: ", data.keys()) # pandas index object

All keys:  Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

#### items()

In [22]:
print("All items: ", list(data.items())) # zip object

All items:  [('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0), ('e', 99.0)]

### values()

In [23]:
print("All values: ", data.values) # numpy array object

All values:  [ 0.25  0.5   0.75  1.   99.  ]

### masking

In [24]:
print("Data[(data > 0.3) & (data < 0.8)]: \n", data[(data>0.3) & (data < 0.8)])

Data[(data > 0.3) & (data < 0.8)]:
 b    0.50
c    0.75
dtype: float64

### fancy indexing

In [25]:
print("Data[['a', 'e']]: \n", data[['a', 'e']])

Data[['a', 'e']]:
 a     0.25
e    99.00
dtype: float64

### iloc vs. loc

In [26]:
# some precaution on the possible confusion if you use explicit integer index
# use explicit index when indexing
data = pd.Series(['a', 'b', 'c'], index=(1, 3, 5))
print("Data[1]: ", data[1])

# use implicit index when slicing
print("Data[1:3]: \n", data[1:3])

# due to this possible confusion due to explicit integer index, pandas
# provide loc and iloc
# loc uses explicit index
print("Data loc [1]: ", data.loc[1])
print("Data loc [1:3]: \n", data.loc[1:3])  # include 3 as well

#iloc uses implicit index
print("Data iloc [1]: ", data.iloc[1])
print("Data iloc [1:3]: \n", data.iloc[1:3])  # does not include 3

# always use iloc for implicit index, for no unnecessary confusion!

Data[1]:  a
Data[1:3]:
 3    b
5    c
dtype: object
Data loc [1]:  a
Data loc [1:3]:
 1    a
3    b
dtype: object
Data iloc [1]:  b
Data iloc [1:3]:
 3    b
5    c
dtype: object

C:\Users\anhng\AppData\Local\Temp\ipykernel_23392\2315341206.py:7: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  print("Data[1:3]: \n", data[1:3])

## DataFrame indexing/slicing/fancy Indexing

In [27]:
some_population_dict = {'Sai Gon': 11111, 
                        'Vung Tau': 22222,
                        'Phan Thiet': 33333,
                        'Vinh Long': 44444}
some_area_dict = {'Sai Gon': 99999, 
                'Vung Tau': 88888,
                'Phan Thiet': 77777,
                'Vinh Long': 66666,
                 'Ben Tre': 33333}
data = pd.DataFrame({'pop': some_population_dict,
                       'area': some_area_dict})

print("==data==")
print(data)

==data==
                pop   area
Sai Gon     11111.0  99999
Vung Tau    22222.0  88888
Phan Thiet  33333.0  77777
Vinh Long   44444.0  66666
Ben Tre         NaN  33333

### dictionary style access

In [28]:
# dataframe can be accessed via dictionary style indexing
print("==Area==")
print(data['area'])

==Area==
Sai Gon       99999
Vung Tau      88888
Phan Thiet    77777
Vinh Long     66666
Ben Tre       33333
Name: area, dtype: int64

### attribute style access

In [29]:
# we can also use attribute-style
print("==Area using attributes==")
print(data.area)
print("Data area is same: ", data.area is data['area'])

==Area using attributes==
Sai Gon       99999
Vung Tau      88888
Phan Thiet    77777
Vinh Long     66666
Ben Tre       33333
Name: area, dtype: int64
Data area is same:  True

### attribute style does not always work

In [30]:
# However!!, keep in mind that attribute style does not always work
# for example, pop is a method, thus data.pop will point to some method instead
print("==Do not use .pop!==")
print("Some pop method: \n", data.pop)
print("Data pop not the same: ", data.pop is data['pop'])

==Do not use .pop!==
Some pop method:
 <bound method DataFrame.pop of                 pop   area
Sai Gon     11111.0  99999
Vung Tau    22222.0  88888
Phan Thiet  33333.0  77777
Vinh Long   44444.0  66666
Ben Tre         NaN  33333>
Data pop not the same:  False

### Feature engineering

In [31]:
print("==Feature engineering with density==")
data['density'] = data['pop'] / data['area']
print(data)

==Feature engineering with density==
                pop   area   density
Sai Gon     11111.0  99999  0.111111
Vung Tau    22222.0  88888  0.250000
Phan Thiet  33333.0  77777  0.428571
Vinh Long   44444.0  66666  0.666667
Ben Tre         NaN  33333       NaN

### iloc and loc

In [32]:
# we cannot use data[0] since we do not have explicit index called 0, use iloc instead
print("==First row using iloc==")
print(data.iloc[0])

==First row using iloc==
pop        11111.000000
area       99999.000000
density        0.111111
Name: Sai Gon, dtype: float64

In [33]:
print("==First three rows, first two columns using iloc==")
print(data.iloc[:3, :2])

==First three rows, first two columns using iloc==
                pop   area
Sai Gon     11111.0  99999
Vung Tau    22222.0  88888
Phan Thiet  33333.0  77777

In [34]:
# use loc for explicit index
print("==Use loc for explicit index==")
print(data.loc[:'Sai Gon', :'pop'])

==Use loc for explicit index==
             pop
Sai Gon  11111.0

In [35]:
# chaining is possible for combine
print("==chain iloc and loc==")
print(data.loc[:'Sai Gon'].iloc[:, :2])

==chain iloc and loc==
             pop   area
Sai Gon  11111.0  99999

#### masking + fancy

In [36]:
print("==masking + fancy==")
print(data.loc[data.density > 20, ['pop', 'density']])

==masking + fancy==
Empty DataFrame
Columns: [pop, density]
Index: []

### Indexing vs. slicing

In [37]:
### some really important convention to keep in mind###
#1.  indexing refers to columns, while slicing refer to rows
print("==Indexing refer to columns==")
print(data['pop'])


print("==Slicing refer to rows==")
print(data['Vung Tau': 'Phan Thiet']) 


print("==Slicing can also use implicit integers==")
print(data[1:3])  # not including 3

print("==masking are done row-wise==")
print(data[data.density > 20])

==Indexing refer to columns==
Sai Gon       11111.0
Vung Tau      22222.0
Phan Thiet    33333.0
Vinh Long     44444.0
Ben Tre           NaN
Name: pop, dtype: float64
==Slicing refer to rows==
                pop   area   density
Vung Tau    22222.0  88888  0.250000
Phan Thiet  33333.0  77777  0.428571
==Slicing can also use implicit integers==
                pop   area   density
Vung Tau    22222.0  88888  0.250000
Phan Thiet  33333.0  77777  0.428571
==masking are done row-wise==
Empty DataFrame
Columns: [pop, area, density]
Index: []

## Broadcasting

In [38]:
import pandas as pd
import numpy as np

rng = np.random.RandomState(42)
df  = pd.DataFrame(rng.randint(0, 10, (3, 4)), 
                 columns = ['A', 'B', 'C', 'D'])
df

   A  B  C  D
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7

### Basic broadcasting

In [39]:
df_new = np.sin(df * np.pi / 4) 
df_new

          A             B         C             D
0 -1.000000  7.071068e-01 -0.707107  1.224647e-16
1 -1.000000  7.071068e-01  1.000000 -1.000000e+00
2 -0.707107  1.224647e-16  0.707107 -7.071068e-01

### Index alignment

In [40]:
area = pd.Series({'Alaska': 111, 'Texas': 222,
                 'California': 333}, name = 'area')
population = pd.Series({'California' : 999, 'Texas': 888,
                       'New York': 777}, name = 'population')

#as you can see, any missing value will be replaced with NaN
print("==population / area==")
print(population / area)

==population / area==
Alaska        NaN
California    3.0
New York      NaN
Texas         4.0
dtype: float64

In [41]:
#similarly
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
print("==A + B==")
print(A + B)

==A + B==
0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [42]:
#we can use fill_value params in pd.add(pd)
print("==A.add(B, fill_value=0)==")  #any missing Nan values will be replaced with 0
print(A.add(B, fill_value = 0))

==A.add(B, fill_value=0)==
0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### Dataframe and series

In [43]:
#Operation between df and series
#common operation is to find difference  of the entire df with one row or column
A  = rng.randint(10, size = (3, 4))
df = pd.DataFrame(A, columns=list('QRST'))
print("==df==")
print(df)

==df==
   Q  R  S  T
0  7  2  5  4
1  1  7  5  1
2  4  0  9  5

In [44]:
print("==df-df.iloc[0]==")
print(df - df.iloc[0])

==df-df.iloc[0]==
   Q  R  S  T
0  0  0  0  0
1 -6  5  0 -3
2 -3 -2  4  1

In [45]:
print("==column-wise==")  #cannot do - , since default is row-wise
print(df.subtract(df['R'], axis=0))

==column-wise==
   Q  R  S  T
0  5  0  3  2
1 -6  0 -2 -6
2  4  0  9  5

## Bài tập 1:
Tải file CSV howlongwelive.csv trong thư mục data vào một DataFrame. Có thể lấy từ kaggle

1. In ra 2 dòng đầu tiên và 2 dòng cuối cùng của DataFrame.

2. In ra kích thước (shape) của DataFrame.

3. In ra tên các đặc trưng (các cột) của DataFrame.

4. In ra bảng thống kê mô tả bằng hàm .describe().

5. Vì cột Hepatitis B có rất nhiều giá trị thiếu (NaN) và có mức tương quan cao với Diphtheria, hãy xóa cột Hepatitis B.
Đồng thời xóa cột Population do có quá nhiều giá trị NaN.

6. Chuyển đổi cột Status sang dạng số:

    0 cho Developing

    1 cho Developed

7. Đổi tên cột thinness 1-19 years thành thinness 10-19 years.

8. Lấy tất cả các cột ngoại trừ Life Expectancy, chuyển sang mảng NumPy và lưu vào biến X.

9. Lấy cột Life Expectancy, chuyển sang mảng NumPy và lưu vào biến y.

In [1]:
import pandas as pd
import numpy as np

# Load dữ liệu
df = pd.read_csv('Life_Expectancy_Data.csv')
print(f"\nĐã load dữ liệu: {df.shape}")


# 1. In 2 dòng đầu và 2 dòng cuối
print("\n1. 2 dòng đầu tiên:")
print(df.head(2))

print("\n2 dòng cuối cùng:")
print(df.tail(2))


# 2. In shape của DataFrame
print(f"\n2. Shape: {df.shape}")
print(f"   - Số dòng: {df.shape[0]}")
print(f"   - Số cột: {df.shape[1]}")


# 3. In tên các cột
print(f"\n3. Tên các cột:")
print(f"   Tổng số: {len(df.columns)}")
for i, col in enumerate(df.columns, 1):
    print(f"   {i:2d}. {col}")


# 4. Thống kê mô tả
print(f"\n4. Thống kê mô tả:")
print(df.describe())


# 5. Xóa cột Hepatitis B và Population
print(f"\n5. Xóa cột Hepatitis B và Population:")
print(f"   Trước khi xóa: {df.shape}")

# Kiểm tra NaN trước 
print(f"   Hepatitis B NaN: {df['Hepatitis B'].isnull().sum()}")
print(f"   Population NaN: {df['Population'].isnull().sum()}")

# Xóa cột (drop với axis=1)
df = df.drop(['Hepatitis B', 'Population'], axis=1)
print(f"   Sau khi xóa: {df.shape}")


# 6. Chuyển Status sang số
print(f"\n6. Chuyển Status sang số:")
print(f"   Trước: {df['Status'].unique()}")
print(f"   Value counts:\n{df['Status'].value_counts()}")

# Sử dụng map() với dictionary
df['Status'] = df['Status'].map({'Developing': 0, 'Developed': 1})
print(f"   Sau: {df['Status'].unique()}")
print(f"   Value counts:\n{df['Status'].value_counts()}")


# 7. Đổi tên cột
print(f"\n7. Đổi tên cột thinness:")
thinness_before = [col for col in df.columns if 'thinness' in col.lower()]
print(f"   Trước: {thinness_before}")

# Sử dụng rename với dictionary
df = df.rename(columns={' thinness  1-19 years': 'thinness 10-19 years'})

thinness_after = [col for col in df.columns if 'thinness' in col.lower()]
print(f"   Sau: {thinness_after}")


# 8. Tạo biến X (features)
print(f"\n8. Tạo biến X (features):")

# Drop cột Life expectancy
X_df = df.drop('Life expectancy ', axis=1)

# Chỉ lấy cột số (select_dtypes như đã học)
X_df = X_df.select_dtypes(include=[np.number])

# Chuyển sang numpy array (sử dụng .values)
X = X_df.values

print(f"   X shape: {X.shape}")
print(f"   X type: {type(X)}")
print(f"   Features: {X_df.columns.tolist()}")
print(f"   5 samples đầu:\n{X[:5]}")


# 9. Tạo biến y (target)
print(f"\n9. Tạo biến y (target):")

# Indexing cột và chuyển sang numpy
y = df['Life expectancy '].values

print(f"   y shape: {y.shape}")
print(f"   y type: {type(y)}")
print(f"   10 giá trị đầu: {y[:10]}")
print(f"   Mean: {np.nanmean(y):.2f}")
print(f"   Min: {np.nanmin(y):.2f}")
print(f"   Max: {np.nanmax(y):.2f}")

Đã load dữ liệu: (2938, 22)

1. 2 dòng đầu tiên:
       Country  Year      Status  Life expectancy   Adult Mortality  \
0  Afghanistan  2015  Developing              65.0            263.0
1  Afghanistan  2014  Developing              59.9            271.0

   infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   ...  \
0             62     0.01               71.279624         65.0      1154  ...
1             64     0.01               73.523582         62.0       492  ...

   Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  Population  \
0    6.0               8.16         65.0        0.1  584.259210  33736494.0
1   58.0               8.18         62.0        0.1  612.696514    327582.0

    thinness  1-19 years   thinness 5-9 years  \
0                   17.2                 17.3
1                   17.5                 17.5

   Income composition of resources  Schooling
0                            0.479       10.1
1                            0.476       10.0

[2 rows x 22 columns]

2 dòng cuối cùng:
       Country  Year      Status  Life expectancy   Adult Mortality  \
2936  Zimbabwe  2001  Developing              45.3            686.0
2937  Zimbabwe  2000  Developing              46.0            665.0

      infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
2936             25     1.72                     0.0         76.0       529
2937             24     1.68                     0.0         79.0      1483

      ...  Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  \
2936  ...   76.0               6.16         75.0       42.1  548.587312
2937  ...   78.0               7.10         78.0       43.5  547.358878

      Population   thinness  1-19 years   thinness 5-9 years  \
2936  12366165.0                    1.6                  1.7
2937  12222251.0                   11.0                 11.2

      Income composition of resources  Schooling
2936                            0.427        9.8
2937                            0.434        9.8

[2 rows x 22 columns]

2. Shape: (2938, 22)
   - Số dòng: 2938
   - Số cột: 22

3. Tên các cột:
   Tổng số: 22
    1. Country
    2. Year
    3. Status
    4. Life expectancy
    5. Adult Mortality
    6. infant deaths
    7. Alcohol
    8. percentage expenditure
    9. Hepatitis B
   10. Measles
   11.  BMI
   12. under-five deaths
   13. Polio
   14. Total expenditure
   15. Diphtheria
   16.  HIV/AIDS
   17. GDP
   18. Population
   19.  thinness  1-19 years
   20.  thinness 5-9 years
   21. Income composition of resources
   22. Schooling

4. Thống kê mô tả:
              Year  Life expectancy   Adult Mortality  infant deaths  \
count  2938.000000       2928.000000      2928.000000    2938.000000
mean   2007.518720         69.224932       164.796448      30.303948
std       4.613841          9.523867       124.292079     117.926501
min    2000.000000         36.300000         1.000000       0.000000
25%    2004.000000         63.100000        74.000000       0.000000
50%    2008.000000         72.100000       144.000000       3.000000
75%    2012.000000         75.700000       228.000000      22.000000
max    2015.000000         89.000000       723.000000    1800.000000

           Alcohol  percentage expenditure  Hepatitis B       Measles   \
count  2744.000000             2938.000000  2385.000000    2938.000000
mean      4.602861              738.251295    80.940461    2419.592240
std       4.052413             1987.914858    25.070016   11467.272489
min       0.010000                0.000000     1.000000       0.000000
25%       0.877500                4.685343    77.000000       0.000000
50%       3.755000               64.912906    92.000000      17.000000
75%       7.702500              441.534144    97.000000     360.250000
max      17.870000            19479.911610    99.000000  212183.000000

              BMI   under-five deaths         Polio  Total expenditure  \
count  2904.000000         2938.000000  2919.000000         2712.00000
mean     38.321247           42.035739    82.550188            5.93819
std      20.044034          160.445548    23.428046            2.49832
min       1.000000            0.000000     3.000000            0.37000
25%      19.300000            0.000000    78.000000            4.26000
50%      43.500000            4.000000    93.000000            5.75500
75%      56.200000           28.000000    97.000000            7.49250
max      87.300000         2500.000000    99.000000           17.60000

       Diphtheria      HIV/AIDS            GDP    Population  \
count  2919.000000  2938.000000    2490.000000  2.286000e+03
mean     82.324084     1.742103    7483.158469  1.275338e+07
std      23.716912     5.077785   14270.169342  6.101210e+07
min       2.000000     0.100000       1.681350  3.400000e+01
25%      78.000000     0.100000     463.935626  1.957932e+05
50%      93.000000     0.100000    1766.947595  1.386542e+06
75%      97.000000     0.800000    5910.806335  7.420359e+06
max      99.000000    50.600000  119172.741800  1.293859e+09

        thinness  1-19 years   thinness 5-9 years  \
count            2904.000000          2904.000000
mean                4.839704             4.870317
std                 4.420195             4.508882
min                 0.100000             0.100000
25%                 1.600000             1.500000
50%                 3.300000             3.300000
75%                 7.200000             7.200000
max                27.700000            28.600000

       Income composition of resources    Schooling
count                      2771.000000  2775.000000
mean                          0.627551    11.992793
std                           0.210904     3.358920
min                           0.000000     0.000000
25%                           0.493000    10.100000
50%                           0.677000    12.300000
75%                           0.779000    14.300000
max                           0.948000    20.700000

5. Xóa cột Hepatitis B và Population:
   Trước khi xóa: (2938, 22)
   Hepatitis B NaN: 553
   Population NaN: 652
   Sau khi xóa: (2938, 20)

6. Chuyển Status sang số:
   Trước: ['Developing' 'Developed']
   Value counts:
Status
Developing    2426
Developed      512
Name: count, dtype: int64
   Sau: [0 1]
   Value counts:
Status
0    2426
1     512
Name: count, dtype: int64

7. Đổi tên cột thinness:
   Trước: [' thinness  1-19 years', ' thinness 5-9 years']
   Sau: ['thinness 10-19 years', ' thinness 5-9 years']

8. Tạo biến X (features):
   X shape: (2938, 18)
   X type: <class 'numpy.ndarray'>
   Features: ['Year', 'Status', 'Adult Mortality', 'infant deaths', 'Alcohol', 'percentage expenditure', 'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure', 'Diphtheria ', ' HIV/AIDS', 'GDP', 'thinness 10-19 years', ' thinness 5-9 years', 'Income composition of resources', 'Schooling']
   5 samples đầu:
[[2.01500000e+03 0.00000000e+00 2.63000000e+02 6.20000000e+01
  1.00000000e-02 7.12796236e+01 1.15400000e+03 1.91000000e+01
  8.30000000e+01 6.00000000e+00 8.16000000e+00 6.50000000e+01
  1.00000000e-01 5.84259210e+02 1.72000000e+01 1.73000000e+01
  4.79000000e-01 1.01000000e+01]
 [2.01400000e+03 0.00000000e+00 2.71000000e+02 6.40000000e+01
  1.00000000e-02 7.35235817e+01 4.92000000e+02 1.86000000e+01
  8.60000000e+01 5.80000000e+01 8.18000000e+00 6.20000000e+01
  1.00000000e-01 6.12696514e+02 1.75000000e+01 1.75000000e+01
  4.76000000e-01 1.00000000e+01]
 [2.01300000e+03 0.00000000e+00 2.68000000e+02 6.60000000e+01
  1.00000000e-02 7.32192427e+01 4.30000000e+02 1.81000000e+01
  8.90000000e+01 6.20000000e+01 8.13000000e+00 6.40000000e+01
  1.00000000e-01 6.31744976e+02 1.77000000e+01 1.77000000e+01
  4.70000000e-01 9.90000000e+00]
 [2.01200000e+03 0.00000000e+00 2.72000000e+02 6.90000000e+01
  1.00000000e-02 7.81842153e+01 2.78700000e+03 1.76000000e+01
  9.30000000e+01 6.70000000e+01 8.52000000e+00 6.70000000e+01
  1.00000000e-01 6.69959000e+02 1.79000000e+01 1.80000000e+01
  4.63000000e-01 9.80000000e+00]
 [2.01100000e+03 0.00000000e+00 2.75000000e+02 7.10000000e+01
  1.00000000e-02 7.09710870e+00 3.01300000e+03 1.72000000e+01
  9.70000000e+01 6.80000000e+01 7.87000000e+00 6.80000000e+01
  1.00000000e-01 6.35372310e+01 1.82000000e+01 1.82000000e+01
  4.54000000e-01 9.50000000e+00]]

9. Tạo biến y (target):
   y shape: (2938,)
   y type: <class 'numpy.ndarray'>
   10 giá trị đầu: [65.  59.9 59.9 59.5 59.2 58.8 58.6 58.1 57.5 57.3]
   Mean: 69.22
   Min: 36.30
   Max: 89.00

## Handling missing data

### np.nan

In [46]:
print("Type of np.nan: ", type(np.nan))
print("Np nan - 1:     ", np.nan - 1) #any operation with nan is nan

Type of np.nan:  <class 'float'>
Np nan - 1:      nan

In [47]:
vals2 = np.array([1, np.nan, 3, 4])
print("Sum:    ", vals2.sum())
print("Nansum: ", np.nansum(vals2))
print("Nanmin: ", np.nanmin(vals2))
print("Nanmax: ", np.nanmax(vals2))

Sum:     nan
Nansum:  8.0
Nanmin:  1.0
Nanmax:  4.0

### Create a pd series with np.nan and None

In [48]:
dfs = pd.Series([1, None, np.nan])
print("Pandas automatically convert None to nans")
print(dfs)

Pandas automatically convert None to nans
0    1.0
1    NaN
2    NaN
dtype: float64

In [49]:
dfs = pd.Series(["Hello", None, np.nan])
print("Pandas do not, since String is object")
print(dfs)

Pandas do not, since String is object
0    Hello
1     None
2      NaN
dtype: object

In [50]:
dfs = pd.Series([True, None, np.nan])
print("Pandas do not, cast Boolean to object")
print(dfs)

Pandas do not, cast Boolean to object
0    True
1    None
2     NaN
dtype: object

### isnull()

In [51]:
#isnull() - check any missing values
dfs = pd.Series([1, np.nan, "hello", None])
print("Is null: ", dfs.isnull())

Is null:  0    False
1     True
2    False
3     True
dtype: bool

### not null

In [52]:
print("==Only data not null==")
print(dfs[dfs.notnull()])

==Only data not null==
0        1
2    hello
dtype: object

### dropna()

In [53]:
print("==Drop all na==")
print(dfs.dropna())  #this is not in place!
print(dfs)  #this will bring back the old copy

==Drop all na==
0        1
2    hello
dtype: object
0        1
1      NaN
2    hello
3     None
dtype: object

In [54]:
#drop columns with na, use axis = 1
df = pd.DataFrame([[1, np.nan, 2],
                  [2, 3, 5],
                  [np.nan, 4, np.nan],
                  [4, np.nan, np.nan]])

print(df.dropna(axis=1))  #default is axis = 0

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [55]:
#drop columns, if all values is nan
df[3] = np.nan  #create new column
print(df.dropna(axis=1, how="all"))

     0    1    2
0  1.0  NaN  2.0
1  2.0  3.0  5.0
2  NaN  4.0  NaN
3  4.0  NaN  NaN

### fillna()

In [56]:
# most of the time, if you have missing values, it is advised
# to drop them.  This is against many opinions.  
# However, the case is that:
# When you replace missing value with mean, you lower the variance
# When you replace with median, you also lower the variance
# when you replace with some value, you introduce noise
# but first, let's see how to replace value

print("==Fill na with 0==")
print(df.fillna(0))  #not in place, reminders!

print("==Fill all na with mean==")
print(df.fillna(df.mean()))

print("replace df.mean() for col 1 with in place")
df[1].fillna(df[1].mean(), inplace=True)  #this is in place!
print(df)

print("==Interpolate==")
print(df.interpolate(method='values'))

==Fill na with 0==
     0    1    2    3
0  1.0  0.0  2.0  0.0
1  2.0  3.0  5.0  0.0
2  0.0  4.0  0.0  0.0
3  4.0  0.0  0.0  0.0
==Fill all na with mean==
          0    1    2   3
0  1.000000  3.5  2.0 NaN
1  2.000000  3.0  5.0 NaN
2  2.333333  4.0  3.5 NaN
3  4.000000  3.5  3.5 NaN
replace df.mean() for col 1 with in place
     0    1    2   3
0  1.0  3.5  2.0 NaN
1  2.0  3.0  5.0 NaN
2  NaN  4.0  NaN NaN
3  4.0  3.5  NaN NaN
==Interpolate==
     0    1    2   3
0  1.0  3.5  2.0 NaN
1  2.0  3.0  5.0 NaN
2  3.0  4.0  5.0 NaN
3  4.0  3.5  5.0 NaN

### Dataframe concatenation

In [57]:
data_numpy    = np.random.rand(3, 2)  #shape 3, 2
index         = ['Bangkok', 'Chiangmai', 'Samut Prakan']
columns       = ['Population', 'Area']
pd_from_numpy = pd.DataFrame(data_numpy, index=index, columns=columns)
print("==First dataframe==")
print(pd_from_numpy)

data_numpy2    = np.random.rand(4, 3)
index2         = ['Bangkok', 'Chiangmai', 'Samut Prakan', 'Pathum Thani']
columns2       = ['HDI', 'Temperature', 'GDP']
pd_from_numpy2 = pd.DataFrame(data_numpy2, index=index2, columns=columns2)
print("==Second dataframe==")
print(pd_from_numpy2)

# do you see something weird, the index is duplicated!
# this is because pandas preserve indices!
# however, the columns are not duplicated...as you can see
print("==Normal concat along axis 1==")
print(pd.concat([pd_from_numpy, pd_from_numpy2], axis=1)) # default join='outer' # in this case it means Full outer join

==First dataframe==
              Population      Area
Bangkok         0.278644  0.439788
Chiangmai       0.518097  0.502111
Samut Prakan    0.464644  0.026832
==Second dataframe==
                   HDI  Temperature       GDP
Bangkok       0.547821     0.876025  0.925966
Chiangmai     0.544494     0.870131  0.702045
Samut Prakan  0.598415     0.607027  0.841260
Pathum Thani  0.786782     0.741872  0.966651
==Normal concat along axis 1==
              Population      Area       HDI  Temperature       GDP
Bangkok         0.278644  0.439788  0.547821     0.876025  0.925966
Chiangmai       0.518097  0.502111  0.544494     0.870131  0.702045
Samut Prakan    0.464644  0.026832  0.598415     0.607027  0.841260
Pathum Thani         NaN       NaN  0.786782     0.741872  0.966651

### Join inner

In [58]:
print("==Concat with join inner==")
print(pd.concat([pd_from_numpy, pd_from_numpy2], axis=1, join='inner'))

==Concat with join inner==
              Population      Area       HDI  Temperature       GDP
Bangkok         0.278644  0.439788  0.547821     0.876025  0.925966
Chiangmai       0.518097  0.502111  0.544494     0.870131  0.702045
Samut Prakan    0.464644  0.026832  0.598415     0.607027  0.841260

## Merging Datasets with ID

In [59]:
left = pd.DataFrame({'ID': ['001', '002', '003', '005'],
                      'DS': ['B', 'B', 'B', 'C+'],
                      'SAD': ['A', 'B', 'C+', 'F']})
left

    ID  DS SAD
0  001   B   A
1  002   B   B
2  003   B  C+
3  005  C+   F

In [60]:
right = pd.DataFrame({'ID': ['001', '002', '003', '004'],
                      'HCI': ['B+', 'A', 'A', 'B+'],
                      'SDQI': ['A', 'A', 'B+', 'B']})
right

    ID HCI SDQI
0  001  B+    A
1  002   A    A
2  003   A   B+
3  004  B+    B

In [61]:
#seems like 004 is gone!  Very similar to inner join
result = pd.merge(left, right, on='ID')  #default is how=inner
result

    ID DS SAD HCI SDQI
0  001  B   A  B+    A
1  002  B   B   A    A
2  003  B  C+   A   B+

In [62]:
#specify how=outer
result = pd.merge(left, right, on='ID', how="outer")  #default is how=inner
result

    ID   DS  SAD  HCI SDQI
0  001    B    A   B+    A
1  002    B    B    A    A
2  003    B   C+    A   B+
3  005   C+    F  NaN  NaN
4  004  NaN  NaN   B+    B

In [63]:
#specify how=left, or right
result = pd.merge(left, right, on='ID', how="left")  #default is how=inner
result

    ID  DS SAD  HCI SDQI
0  001   B   A   B+    A
1  002   B   B    A    A
2  003   B  C+    A   B+
3  005  C+   F  NaN  NaN

## Aggregation

In [64]:
df = pd.DataFrame([('bird', 'Falconiformes', 389.0),
                    ('bird', 'Psittaciformes', 24.0),
                    ('mammal', 'Carnivora', 80.2),
                    ('mammal', 'Primates', np.nan),
                    ('mammal', 'Carnivora', 58)],
                   index=['falcon', 'parrot', 'lion', 'monkey', 'leopard'],
                   columns=('class', 'order', 'max_speed'))
df

          class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [65]:
grouped = df.groupby('class')  #return a special view as DataFrameGroupByObject
grouped.sum()

C:\Users\anhng\AppData\Local\Temp\ipykernel_23392\2388972087.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped.sum()

        max_speed
class
bird        413.0
mammal      138.2

In [66]:
grouped = df.groupby('order')  #return a special view as DataFrameGroupByObject
grouped.sum()

C:\Users\anhng\AppData\Local\Temp\ipykernel_23392\1839674679.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped.sum()

                max_speed
order
Carnivora           138.2
Falconiformes       389.0
Primates              0.0
Psittaciformes       24.0

In [67]:
grouped = df.groupby(['class', 'order'])
grouped.sum()

                       max_speed
class  order
bird   Falconiformes       389.0
       Psittaciformes       24.0
mammal Carnivora           138.2
       Primates              0.0

In [68]:
df.groupby(['class'])['max_speed'].median()

class
bird      206.5
mammal     69.1
Name: max_speed, dtype: float64

In [69]:
import seaborn as sns
planets = sns.load_dataset('planets')
print("Shape: ", planets.shape)
print("First five rows: ")
print(planets.head())

print("==Built in Pandas simple aggregations==")
print(planets.mean())
# print(planets.median())
# print(planets.min())
# print(planets.max())
# print(planets.std())
# print(planets.var())
# print(planets.sum())

print("==Mean (axis=1)==")
print(planets.mean(axis=1))

print("==Describe==")
print(planets.describe())

Shape:  (1035, 6)
First five rows:
            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009
==Built in Pandas simple aggregations==
number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64
==Mean (axis=1)==
0       472.160000
1       588.586800
2       559.488000
3       492.810000
4       531.238000
           ...
1030    545.735377
1031    539.653966
1032    546.297881
1033    576.531271
1034    568.296939
Length: 1035, dtype: float64
==Describe==
            number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

C:\Users\anhng\AppData\Local\Temp\ipykernel_23392\4199839939.py:8: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(planets.mean())
C:\Users\anhng\AppData\Local\Temp\ipykernel_23392\4199839939.py:17: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(planets.mean(axis=1))

In [70]:
planets.groupby('method').sum()

,number,orbital_period,mass,distance,year
method,,,,,
Astrometry,2,1.262360e+03,0.00000,35.75,4023
Eclipse Timing Variations,15,4.276480e+04,10.25000,1261.44,18090
Imaging,50,1.418973e+06,0.00000,2166.91,76347
Microlensing,27,2.207500e+04,0.00000,41440.00,46225
Orbital Brightness Modulation,5,2.127920e+00,0.00000,2360.00,6035
Pulsar Timing,11,3.671511e+04,0.00000,1200.00,9992
Pulsation Timing Variations,1,1.170000e+03,0.00000,0.00,2007
Radial Velocity,952,4.553151e+05,1341.65638,27348.11,1110158
Transit,776,8.377523e+03,1.47000,134242.77,798461
Transit Timing Variations,9,2.393505e+02,0.00000,3313.00,8050

In [71]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [72]:
# The GroupBy object supports direct iteration over the groups, 
# returning each group as a Series or DataFrame:
for (method, group) in planets.groupby('method'):
    print("{0:30s} shape={1}".format(method, group.shape))

Astrometry                     shape=(2, 6)
Eclipse Timing Variations      shape=(9, 6)
Imaging                        shape=(38, 6)
Microlensing                   shape=(23, 6)
Orbital Brightness Modulation  shape=(3, 6)
Pulsar Timing                  shape=(5, 6)
Pulsation Timing Variations    shape=(1, 6)
Radial Velocity                shape=(553, 6)
Transit                        shape=(397, 6)
Transit Timing Variations      shape=(4, 6)

In [73]:
planets.describe()

            number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

GroupBy objects have aggregate(), filter(), transform(), and apply() methods that efficiently implement a variety of useful operations before combining the grouped data.  For the purpose of the following subsections, we'll use this DataFrame:

In [74]:
# aggregate() can take a string, a function or a list thereof, and compute
# all aggregates at once
planets.groupby('method')['orbital_period'].aggregate(
    ['min', np.median, max, np.mean, np.std, 'count'])

,min,median,max,mean,std,count
method,,,,,,
Astrometry,246.360000,631.180000,1016.000000,631.180000,544.217663,2
Eclipse Timing Variations,1916.250000,4343.500000,10220.000000,4751.644444,2499.130945,9
Imaging,4639.150000,27500.000000,730000.000000,118247.737500,213978.177277,12
Microlensing,1825.000000,3300.000000,5100.000000,3153.571429,1113.166333,7
Orbital Brightness Modulation,0.240104,0.342887,1.544929,0.709307,0.725493,3
Pulsar Timing,0.090706,66.541900,36525.000000,7343.021201,16313.265573,5
Pulsation Timing Variations,1170.000000,1170.000000,1170.000000,1170.000000,NaN,1
Radial Velocity,0.736540,360.200000,17337.500000,823.354680,1454.926210,553
Transit,0.355000,5.714932,331.600590,21.102073,46.185893,397
Transit Timing Variations,22.339500,57.011000,160.000000,79.783500,71.599884,3

In [75]:
# take only elements that belong to group with x orbital period of std less than 3
new_planets = planets.groupby('method').filter(lambda x: x['orbital_period'].std() < 3)
new_planets.head()

,method,number,orbital_period,mass,distance,year
787,Orbital Brightness Modulation,2,0.240104,NaN,1180.0,2011
788,Orbital Brightness Modulation,2,0.342887,NaN,1180.0,2011
792,Orbital Brightness Modulation,1,1.544929,NaN,NaN,2013

In [76]:
# look at each record
new_planets.loc[787]

method            Orbital Brightness Modulation
number                                        2
orbital_period                         0.240104
mass                                        NaN
distance                                 1180.0
year                                       2011
Name: 787, dtype: object

In [77]:
# perform apply for each group
planets.groupby('method').apply(lambda x: x.describe())

                                 number  orbital_period  mass     distance  \
method
Astrometry                count    2.00        2.000000   0.0     2.000000
                          mean     1.00      631.180000   NaN    17.875000
                          std      0.00      544.217663   NaN     4.094148
                          min      1.00      246.360000   NaN    14.980000
                          25%      1.00      438.770000   NaN    16.427500
...                                 ...             ...   ...          ...
Transit Timing Variations min      2.00       22.339500   NaN   339.000000
                          25%      2.00       39.675250   NaN   597.000000
                          50%      2.00       57.011000   NaN   855.000000
                          75%      2.25      108.505500   NaN  1487.000000
                          max      3.00      160.000000   NaN  2119.000000

                                       year
method
Astrometry                count     2.00000
                          mean   2011.50000
                          std       2.12132
                          min    2010.00000
                          25%    2010.75000
...                                     ...
Transit Timing Variations min    2011.00000
                          25%    2011.75000
                          50%    2012.50000
                          75%    2013.25000
                          max    2014.00000

[80 rows x 5 columns]

In [78]:
# we can also do something fancy like this
grouped = planets.groupby('method')['orbital_period']

def some_func(group):
    return pd.DataFrame({'original': group,
                        'demeaned': group - group.mean()})

grouped.apply(some_func)

C:\Users\anhng\AppData\Local\Temp\ipykernel_23392\1369668585.py:8: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  grouped.apply(some_func)

        original    demeaned
0     269.300000 -554.054680
1     874.774000   51.419320
2     763.000000  -60.354680
3     326.030000 -497.324680
4     516.220000 -307.134680
...          ...         ...
1030    3.941507  -17.160566
1031    2.615864  -18.486209
1032    3.191524  -17.910549
1033    4.125083  -16.976990
1034    4.187757  -16.914316

[1035 rows x 2 columns]

## Bài Tập 2

1. Kiểm tra xem mỗi cột có bao nhiêu giá trị bị thiếu (missing data / NaN).

2. Xử lý tất cả dữ liệu bị thiếu bằng cách thay thế bằng giá trị trung bình (mean) của từng cột tương ứng.

3. Thực hiện groupby theo quốc gia (Country).

    - Quốc gia nào có tuổi thọ trung bình thấp nhất?

    - Quốc gia nào có tuổi thọ trung bình cao nhất?

4. Thực hiện groupby theo Status (Developed / Developing).

    - Có sự khác biệt rõ rệt nào về tuổi thọ trung bình giữa các quốc gia phát triển và đang phát triển hay không?

5. Tạo một DataFrame mới bằng tay gồm 2 cột:

    - Cột thứ nhất là ID, có giá trị giống với cột Country

    - Cột thứ hai là Noise_level, điền giá trị ngẫu nhiên (tùy ý)

6. Gộp (merge) hai DataFrame lại với nhau dựa trên cột ID.

In [2]:
import pandas as pd
import numpy as np

# Load dữ liệu
df = pd.read_csv('Life_Expectancy_Data.csv')


# 1. Kiểm tra missing data
print(f"\n1. Kiểm tra missing data:")
print("\nSố lượng NaN:")
print(df.isnull().sum())

print("\nPhần trăm NaN:")
print((df.isnull().sum() / len(df) * 100).round(2))


# 2. Xử lý missing data bằng mean
print(f"\n2. Xử lý missing data bằng mean:")
print(f"   Trước fillna: Tổng NaN = {df.isnull().sum().sum()}")

# Chỉ fillna cho cột số
numeric_cols = df.select_dtypes(include=[np.number]).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

print(f"   Sau fillna: Tổng NaN = {df.isnull().sum().sum()}")


# 3. Groupby theo Country
print(f"\n3. Groupby theo Country:")

# Groupby và tính mean
grouped = df.groupby('Country')['Life expectancy ']
life_exp_by_country = grouped.mean().sort_values()

print("\n10 quốc gia tuổi thọ THẤP NHẤT:")
print(life_exp_by_country.head(10))

print("\n10 quốc gia tuổi thọ CAO NHẤT:")
print(life_exp_by_country.tail(10))

# Sử dụng idxmin() và idxmax() (đã học)
print(f"\nThấp nhất: {life_exp_by_country.idxmin()} ({life_exp_by_country.min():.2f})")
print(f"Cao nhất: {life_exp_by_country.idxmax()} ({life_exp_by_country.max():.2f})")


# 4. Groupby theo Status
print(f"\n4. Groupby theo Status:")

# Groupby và aggregate nhiều functions
grouped_status = df.groupby('Status')['Life expectancy ']
stats = grouped_status.aggregate(['count', 'mean', 'median', 'std', 'min', 'max'])

print("\nThống kê:")
print(stats)

# Tính chênh lệch
developed_mean = stats.loc['Developed', 'mean']
developing_mean = stats.loc['Developing', 'mean']
diff = developed_mean - developing_mean

print(f"\nDeveloped: {developed_mean:.2f}")
print(f"Developing: {developing_mean:.2f}")
print(f"Chênh lệch: {diff:.2f} ({diff/developing_mean*100:.1f}%)")

if diff > 5:
    print("Có sự khác biệt rõ rệt")


# 5. Tạo DataFrame mới
print(f"\n5. Tạo DataFrame mới:")

# Lấy unique countries
unique_countries = df['Country'].unique()

# Tạo DataFrame từ dictionary (như đã học)
np.random.seed(42)
df_noise = pd.DataFrame({
    'ID': unique_countries,
    'Noise_level': np.random.uniform(30, 100, size=len(unique_countries))
})

print(f"   Shape: {df_noise.shape}")
print(f"\n10 dòng đầu:")
print(df_noise.head(10))


# 6. Merge hai DataFrame
print(f"\n6. Merge DataFrame:")

# Sử dụng merge với left_on, right_on
df_merged = df.merge(df_noise, left_on='Country', right_on='ID', how='left')

print(f"   df: {df.shape}")
print(f"   df_noise: {df_noise.shape}")
print(f"   df_merged: {df_merged.shape}")

print(f"\n10 dòng sau merge:")
cols = ['Country', 'Year', 'Status', 'Life expectancy ', 'ID', 'Noise_level']
print(df_merged[cols].head(10))

print(f"\nMerge thành công: {df_merged['Noise_level'].notna().sum() == len(df_merged)}")


# Lưu kết quả

df_merged.to_csv('Life_Expectancy_Data_merged.csv', index=False)
print("Đã lưu Life_Expectancy_Data_merged.csv")

1. Kiểm tra missing data:

Số lượng NaN:
Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

Phần trăm NaN:
Country                             0.00
Year                                0.00
Status                              0.00
Life expectancy                     0.34
Adult Mortality                     0.34
infant deaths                       0.00
Alcohol                             6.60
percentage expenditure              0.00
Hepatitis B                        18.82
Measles                             0.00
 BMI                                1.16
under-five deaths                   0.00
Polio                               0.65
Total expenditure                   7.69
Diphtheria                          0.65
 HIV/AIDS                           0.00
GDP                                15.25
Population                         22.19
 thinness  1-19 years               1.16
 thinness 5-9 years                 1.16
Income composition of resources     5.68
Schooling                           5.55
dtype: float64

2. Xử lý missing data bằng mean:
   Trước fillna: Tổng NaN = 2563
   Sau fillna: Tổng NaN = 0

3. Groupby theo Country:

10 quốc gia tuổi thọ THẤP NHẤT:
Country
Sierra Leone                46.11250
Central African Republic    48.51250
Lesotho                     48.78125
Angola                      49.01875
Malawi                      49.89375
Chad                        50.38750
Côte d'Ivoire               50.38750
Zimbabwe                    50.48750
Swaziland                   51.32500
Nigeria                     51.35625
Name: Life expectancy , dtype: float64

10 quốc gia tuổi thọ CAO NHẤT:
Country
Canada         81.68750
Norway         81.79375
Australia      81.81250
Spain          82.06875
Italy          82.18750
France         82.21875
Switzerland    82.33125
Iceland        82.44375
Sweden         82.51875
Japan          82.53750
Name: Life expectancy , dtype: float64

Thấp nhất: Sierra Leone (46.11)
Cao nhất: Japan (82.54)

4. Groupby theo Status:

Thống kê:
            count       mean  median       std   min   max
Status
Developed     512  79.197852   79.25  3.930942  69.9  89.0
Developing   2426  67.120177   69.05  8.988524  36.3  89.0

Developed: 79.20
Developing: 67.12
Chênh lệch: 12.08 (18.0%)
Có sự khác biệt rõ rệt

5. Tạo DataFrame mới:
   Shape: (193, 2)

10 dòng đầu:
                    ID  Noise_level
0          Afghanistan    56.217808
1              Albania    96.550001
2              Algeria    81.239576
3               Angola    71.906094
4  Antigua and Barbuda    40.921305
5            Argentina    40.919616
6              Armenia    34.065853
7            Australia    90.632330
8              Austria    72.078051
9           Azerbaijan    79.565080

6. Merge DataFrame:
   df: (2938, 22)
   df_noise: (193, 2)
   df_merged: (2938, 24)

10 dòng sau merge:
       Country  Year      Status  Life expectancy            ID  Noise_level
0  Afghanistan  2015  Developing              65.0  Afghanistan    56.217808
1  Afghanistan  2014  Developing              59.9  Afghanistan    56.217808
2  Afghanistan  2013  Developing              59.9  Afghanistan    56.217808
3  Afghanistan  2012  Developing              59.5  Afghanistan    56.217808
4  Afghanistan  2011  Developing              59.2  Afghanistan    56.217808
5  Afghanistan  2010  Developing              58.8  Afghanistan    56.217808
6  Afghanistan  2009  Developing              58.6  Afghanistan    56.217808
7  Afghanistan  2008  Developing              58.1  Afghanistan    56.217808
8  Afghanistan  2007  Developing              57.5  Afghanistan    56.217808
9  Afghanistan  2006  Developing              57.3  Afghanistan    56.217808

Merge thành công: True
Đã lưu Life_Expectancy_Data_merged.csv